name: CI
on:
  schedule:
    - cron: "0 4,8,12,16,20 * * *"
    - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
      GIT: ${{secrets.GIT}}
      WAIFUIM: ${{secrets.WAIFUIM}}
      RUNNUM: ${{ github.run_number }}
      REPO: ${{ github.repository }}
    steps:
      - name: GIT clone the main repo !
        run: |
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          cd /home/runner/work/${{ github.event.repository.name }}
          git clone https://github.com/${{ github.repository }}.git
      - name: Run a multi-line script
        run: |
          BOTDIR="/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
          cd $BOTDIR
          chmod +x $BOTDIR/main.sh
          timeout $(( 4 * 60 * 60 - 60 ))s bash -c "bash ${BOTDIR}/main.sh" || exit
          kill $!
          git branch sub &>/dev/null
          git checkout 
          git branch --set-upstream-to=origin/sub
          git add --all
          git config --global user.email "hakurei@asia.com"
          git config --global user.name "hakureii"
          git commit -am 'remote sync'
          git config pull.rebase false
          git pull origin main
          git push https://hakureii:${GIT}@github.com/${REPO}.git sub
