name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
      GIT: ${{secrets.GIT}}
      RUNNUM: ${{ github.run_number }}
    steps:
      - name: GIT clone the main repo !
        run: |
          rm -rf /home/runner/work/izuku
          cd /home/runner/work
          git clone https://github.com/hakureii/izuku.git
      - name: Run a multi-line script
        run: |
          BOTDIR="/home/runner/work/izuku"
          cd $BOTDIR
          chmod +x $BOTDIR/main.sh
          timeout $(( 4 * 60 * 60 ))s bash -c "bash ${BOTDIR}/main.sh"
          git add --all
          git config --global user.email "hakurei@asia.com"
          git config --global user.name "hakureii"
          git commit -am 'izuku remote sync'
          git push https://hakureii:${GIT}@github.com/hakureii/izuku.git
